# The Docker image that will be used to build your app
image: node:18
pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm run docs:build
  artifacts: # 制品 /ˈɑːtɪfækt/
    paths:
      - public
  only:
    - dev-docs